### ISSUE TITLE
Mobile Live Ops 

### ISSUE THREAD

**Issue by gcornish** [jnusser/Crusade#5]

**Comment by gcornish** [comment]
@jnusser Waiting on a name everyone has agreed on. Next steps are:
1. Purchase Domain Name
2. Create Landing Page

**Comment by jnusser** [comment]
What did we find out on the domain assignment delay?

On Mon, Nov 10, 2014 at 11:27 AM, gcornish notifications@github.com wrote:

> @jnusser https://github.com/jnusser Waiting on a name everyone has
> agreed on. Next steps are:
> 1. Purchase Domain Name
> 2. Create Landing Page
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jnusser/Marketing/issues/5#issuecomment-62439506.

## 

_Jeremy Nusser_
SVP, Growth / Business Development
415.300.0524 (m)
skype: jnusser
jeremy@fuelpowered.com

**Comment by gcornish** [comment]
Mark said we should be able to receive emails? It wasn't clear. I pinged him again this morning to see what the word was on getting us onto a google group. Will let you know more as the info comes in.
